function Y = predict(w,X)
% This function computes the predicted labels generated by the logistic
% regression model with given weights
%
% inputs: w: weight vector in R^d for logistic regression model
%         X: n-by-d image matrix; each row is an image in R^d
% ouput:  Y: predicted label vector for the n images in X by the logistic 
%            regression model using the weights w  

Y  = sign(X*w); % y in {-1,1}^n is a column vector 

end
